config: 
  plugins:
    metrics-by-endpoint: {}
  target: 'http://localhost:1010'
  phases: 
    - duration: 20
      arrivalRate: 10
scenarios: 
  - name: 'Sessions Flow (register + login)'
    flow: 
      - log: 'Creando un usuario de prueba en /api/test/user'
      - get: 
          url: /api/test/user
          capture: 
            - json: "$.first_name"
              as: "first_name"
            - json: "$.last_name"
              as: "last_name"
            - json: "$.email"
              as: "email"
            - json: "$.password"
              as: "password"
      - log: 'Registro de usuario en /api/sessions/register'
      - post: 
          url: /api/sessions/register
          json: 
            first_name: "{{first_name}}"
            last_name: "{{last_name}}"
            email: "{{email}}"
            password: "{{password}}"
            role: "{{role}}"

      - think: 2
      - log: "Login de usuario"
      - post: 
          url: /api/sessions/login
          json: 
            email: "{{email}}"
            password: "{{password}}"


          
